### ISSUE TITLE
HiBench 3.0.0 on CDH 5.3

### ISSUE THREAD

**Issue by cupdike** [intel-hadoop/HiBench#112] opened 2015-07-10 17:56 UTC
Trying to run on CDH 5.3, I encounter this error running bayes :
    
    Found interface org.apache.hadoop.mapreduce.Counter, but class was expected
Thinking this is related to mahout 0.7 not being supported, and seeing the comment in common/hibench/mahout/pom.xml that says:

     If you wanna run on a cdh cluster or hadoop 2, you may need to wget mahout cdh version(http://archive.cloudera.com/cdh5/cdh/5/mahout-0.9-cdh5.1.0.tar.gz).
I go get that file and drop it in under .mahout/target (machine is not on the internet).  Then I do a mvn clean process-sources and try to rerun bayes.  Now I get: 

    Error: The mahout bin file hasn't be downloaded by maven, please check!
I see that bin/hibench_config.sh seems hardcoded to mahout 0.7.  I've tried hacking around in there but I'm not sure what is required to really get things rewired with 0.9.  

What do I need to do? TIA

**Comment by cupdike** [comment] 2015-07-10 18:50
Well I tried unpacking the mahout cdh jar and setting MAHOUT_HOME to that dir in hibench_config.sh but that didn't work.  So I hacked up these two:

    export MAHOUT_RELEASE=mahout-0.9-cdh5.1.0
    export MAHOUT_EXAMPLE_JOB="mahout-examples-0.9-cdh5.1.0-job.jar"

And now it runs.

**Comment by adrian-wang** [comment] 2015-08-25 01:24
Close it since it has been resolved. Thanks @cupdike !

**Closed by adrian-wang** 2015-08-25 01:24 UTC

**Comment by yncxcw** [comment] 2016-02-22 23:51
I also have this issue when I deployed hadoop-2.7.1 while running Bayes, I found this problems was caused by the incompatibility between hadoop-2.7.1 and mahout-0.9, I replaced mahout-0.9 with mahout-0.10.0. and now it works
